const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{background: 0},
	{arac: 0},
	{gezegenBtn: 0},
	{solgrafik: 0},
	{ParemetreBarı: 0},
	{dikBtn: 0},
	{Dik2: 0},
	{hızbarbt: 0},
	{yükseklikbt: 0},
	{kinetikenerjibt: 0},
	{potansiyelenerjibt: 0},
	{ısıenerjisibt: 0},
	{toplamenerjibt: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	arac: class extends self.ISpriteInstance {},
	gezegenBtn: class extends self.ISpriteInstance {},
	solgrafik: class extends self.ISpriteInstance {},
	ParemetreBarı: class extends self.ISpriteInstance {},
	dikBtn: class extends self.ISpriteInstance {},
	Dik2: class extends self.ISpriteInstance {},
	hızbarbt: class extends self.ISpriteInstance {},
	yükseklikbt: class extends self.ISpriteInstance {},
	kinetikenerjibt: class extends self.ISpriteInstance {},
	potansiyelenerjibt: class extends self.ISpriteInstance {},
	ısıenerjisibt: class extends self.ISpriteInstance {},
	toplamenerjibt: class extends self.ISpriteInstance {}
}